### ISSUE TITLE
Data reload

### ISSUE THREAD

**Issue by MichalBryxi** [aomra015/ember-cli-chart#19] opened 2015-05-29 08:56 UTC
I'm using 2.0.1 version of this addon and I'm having problems with data not being reflected in (bar)chart after change.

1) I bind a propery with the data to the component.
2) I change the data so that I remove "columns" from the data set and remove corresponding labels. Also because it's different data set, remaining columns values changes.
3) The graph reflects new values - the bars re-renders with nice animation. Problem is that the graph never removes the columns for which I don't provide data anymore. It also never adds new columns if my dataset expands.

Is this a bug or should I triger re-rendering somehow?

**Comment by aomra015** [comment] 2015-05-30 15:19
@MichalBryxi I would have to confirm the bug but chances are it's a bug. The problem is that Chartjs doesn't have a very robust system for updating a chart's data so in this addon we've had to do that ourselves. It's obvious that our implementation needs work.

**Comment by MichalBryxi** [comment] 2015-05-30 19:23
There is [`.update()`](http://www.chartjs.org/docs/) method to force re-rendering. Which might be called upon data change.

**Comment by aomra015** [comment] 2015-05-31 15:13
The problem is that before calling `update` we have to update the dataset as the example in the documentation shows. Each chart has its own dataset structure. We do all of that in https://github.com/aomra015/ember-cli-chart/blob/master/addon/chart-data-updater.js

**Comment by philwilson** [comment] 2015-06-05 09:47
I have just started using this and come across the same issue. I think I have a simple fix for it and will create a pull request.

**Comment by aomra015** [comment] 2015-06-06 16:08
The good news is that ChartJS version 2.0 alpha is out and they've improved `update` so that we don't have to traversing the chart object to update the data. So when 2.0 is released this addon can just use that functionality.

**Comment by cuzi** [comment] 2015-06-10 14:44
I have big problem with that issue too, if philwilson fix is do the job please accept the changes..
thanks!

**Comment by aomra015** [comment] 2015-06-17 11:40
this should be fixed by https://github.com/aomra015/ember-cli-chart/commit/a178e3bd303b0b1b12864047ac09350345b38305

**Comment by MichalBryxi** [comment] 2015-06-17 13:27
Thanks for this one. 

Unfortunatelly I'm seeing a bug: If I add new column to bar graph, it's re-rendered correctly. If I remove column from bar graph, then the old data remains.

```
// change "data" property - add or remove columns
{{ember-chart type="Bar" data=data}}
```

**Comment by aomra015** [comment] 2015-06-17 21:36
hmm interesting. I'll add a test for this to see if I can replicate the issue.

**Comment by MichalBryxi** [comment] 2015-06-17 22:08
Let me know if you have any issues replicating this. Can provide github code which suffers from this. Or if you want I can try to craft jsbin for you.

**Comment by Orthocenter** [comment] 2015-06-21 03:54
I also saw that bug(previous data still remain there after I remove a column) on line graph. Any solution?

**Comment by Orthocenter** [comment] 2015-06-21 04:19
I find out a temporary way to solve this problem.
In template file:
```
          {{#if display}}
            {{ember-chart type=type data=data options=options}}
          {{else}}
            {{ember-chart type=type data=data options=options}}
          {{/if}}
```
And toggle `display` every time after data updated.

**Closed** 2015-06-28 18:24 UTC
